"""Export the Markdown answers generated by app.py to CSV and DOCX."""

import argparse
import csv
import re
from pathlib import Path

from docx import Document
from docx.shared import Pt


ANSWER_BLOCK = re.compile(
    r"^## (?P<number>\d+)\. (?P<category>.+?)\n\n"
    r"\*\*คำถาม:\*\* (?P<question>.+?)\n\n"
    r"\*\*คำตอบ:\*\* (?P<answer>.*?)(?=^## |\Z)",
    flags=re.MULTILINE | re.DOTALL,
)


def parse_answers(markdown_path: Path) -> list[dict[str, str]]:
    if not markdown_path.is_file():
        raise FileNotFoundError(f"ไม่พบไฟล์คำตอบ: {markdown_path}")

    content = markdown_path.read_text(encoding="utf-8")
    answers = [
        {key: value.strip() for key, value in match.groupdict().items()}
        for match in ANSWER_BLOCK.finditer(content)
    ]
    if not answers:
        raise ValueError("ไม่พบคำตอบในรูปแบบที่ส่งออกได้")
    return answers


def write_csv(answers: list[dict[str, str]], output_path: Path) -> None:
    with output_path.open("w", encoding="utf-8-sig", newline="") as output_file:
        writer = csv.DictWriter(
            output_file,
            fieldnames=["ลำดับ", "หมวด", "คำถาม", "คำตอบ"],
        )
        writer.writeheader()
        for answer in answers:
            writer.writerow(
                {
                    "ลำดับ": answer["number"],
                    "หมวด": answer["category"],
                    "คำถาม": answer["question"],
                    "คำตอบ": answer["answer"],
                }
            )


def write_docx(answers: list[dict[str, str]], output_path: Path) -> None:
    document = Document()
    document.core_properties.title = "คำตอบจาก Solar Cell RAG"
    document.styles["Normal"].font.name = "TH Sarabun New"
    document.styles["Normal"].font.size = Pt(14)

    document.add_heading("คำตอบจาก Solar Cell RAG", level=0)
    document.add_paragraph(f"จำนวนคำถาม: {len(answers)} ข้อ")

    for answer in answers:
        document.add_heading(f"{answer['number']}. {answer['category']}", level=1)
        question = document.add_paragraph()
        question.add_run("คำถาม: ").bold = True
        question.add_run(answer["question"])
        response = document.add_paragraph()
        response.add_run("คำตอบ: ").bold = True
        response.add_run(answer["answer"])

    document.save(output_path)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Solar Cell RAG answers")
    parser.add_argument("--input", type=Path, default=Path("Answers.md"))
    parser.add_argument("--csv", type=Path, default=Path("Answers.csv"))
    parser.add_argument("--docx", type=Path, default=Path("Answers.docx"))
    args = parser.parse_args()

    answers = parse_answers(args.input)
    write_csv(answers, args.csv)
    write_docx(answers, args.docx)
    print(f"Exported {len(answers)} answers to {args.csv} and {args.docx}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
